### ISSUE TITLE
Is there any support at cyclic.sh?

### ISSUE THREAD

**Issue by ilshm** [cyclic-software/express-hello-world#45]
I have recently changed my github account username to ilyabumblebee, but my cyclic account still has an old one bEgemot32015, that's why I can only access my account page.
When I try to open https://app.cyclic.sh/#/deploy or any other page that is linked with my account, I have unlimited load.
I have no deployments so you can do anything to my account
Please delete my account or fix it.
Thanks!

**Comment by seekayel** [comment]
Please email support at cyclic.sh from the email on your github account.
