### ISSUE TITLE
How to have cyclic's 'npm install' omit dev dependencies?

### ISSUE THREAD

**Issue by cagross** [cyclic-software/express-hello-world#9]
Hi guys.  I have a technical question regarding deployment of a Node project.

In my cyclic deployment logs, it indicates:

*WARN config production Use `--omit=dev` instead.*

See screenshot [here](https://i.imgur.com/1oyA5It.jpeg).  How can I resolve that?  In other words, since this is the production version of my app, I do indeed want any `npm install` step by cyclic to omit the dev dependencies--how can I do that?

I've already set the environmental variable NODE_ENV on cyclic to `production`.

Thanks in advance.

PS This question is not directly related to this express-hello-world repo.  But it was the closest repo to my actual project, so I posted here.  Let me know if there's a better place for this question.  I posted it to the Discord general channel, but it didn't get any replies (it was over the weekend, so maybe it got lost in the shuffle).

**Comment by seekayel** [comment]
This is a confusing error message. It is on us to fix it for you. Not to worry, we install all `dependencies` & `devDependencies`, run your `build` script, then prune any `devDependencies`.

Hopefully that makes sense.

**Comment by cagross** [comment]
OK no worries, thanks for clarifying.  This app is just a small side project for me, so I don't have any real need for this to be fixed.  I was just asking more for the future, in case I ever needed to deploy a more critical app.  

> Not to worry, we install all dependencies & devDependencies, run your build script, then prune any devDependencies.

Yep gotcha.  What I was more concerned with though was time-to-deploy.  With a larger app, omitting the devDependencies on `npm install` could save a little time in theory.  But I haven't done any real tests, so I'm not exactly sure when one would start seeing gains from that.  

Anyway though, as I mentioned, it's no concern for me at the moment, or for the foreseeable future.  Thanks very much for the reply.  I'll close this.
